2021-03-05 13:28:40 INFO  ConnectionUtil:43 - connection successful
2021-03-05 13:28:40 INFO  ConnectionUtil:53 - connected to db
2021-03-05 13:28:40 WARN  UserDAOImpl:42 - Unable to insert user
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.insert(UserDAOImpl.java:37)
	at com.revature.services.UserService.insert(UserService.java:16)
	at com.revature.services.UserService.main(UserService.java:57)
2021-03-05 13:39:27 INFO  ConnectionUtil:43 - connection successful
2021-03-05 13:39:27 INFO  ConnectionUtil:53 - connected to db
2021-03-05 14:35:31 INFO  ConnectionUtil:42 - Connection successful
2021-03-05 14:35:31 INFO  ConnectionUtil:52 - Connected to db
2021-03-05 14:35:31 WARN  UserDAOImpl:85 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "employee" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.findAll(UserDAOImpl.java:69)
	at com.revature.services.UserService.findAll(UserService.java:25)
	at com.revature.services.UserService.main(UserService.java:56)
2021-03-05 14:36:44 INFO  ConnectionUtil:42 - Connection successful
2021-03-05 14:36:44 INFO  ConnectionUtil:52 - Connected to db
