2021-03-05 13:28:40 INFO  ConnectionUtil:43 - connection successful
2021-03-05 13:28:40 INFO  ConnectionUtil:53 - connected to db
2021-03-05 13:28:40 WARN  UserDAOImpl:42 - Unable to insert user
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.insert(UserDAOImpl.java:37)
	at com.revature.services.UserService.insert(UserService.java:16)
	at com.revature.services.UserService.main(UserService.java:57)
2021-03-05 13:39:27 INFO  ConnectionUtil:43 - connection successful
2021-03-05 13:39:27 INFO  ConnectionUtil:53 - connected to db
2021-03-05 14:35:31 INFO  ConnectionUtil:42 - Connection successful
2021-03-05 14:35:31 INFO  ConnectionUtil:52 - Connected to db
2021-03-05 14:35:31 WARN  UserDAOImpl:85 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "employee" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.findAll(UserDAOImpl.java:69)
	at com.revature.services.UserService.findAll(UserService.java:25)
	at com.revature.services.UserService.main(UserService.java:56)
2021-03-05 14:36:44 INFO  ConnectionUtil:42 - Connection successful
2021-03-05 14:36:44 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:16:04 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:16:04 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:16:04 WARN  ExpenseDAOImpl:106 - Unable to retrieve all expenses
org.postgresql.util.PSQLException: The column name authorId was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.ExpenseDAOImpl.findAll(ExpenseDAOImpl.java:88)
	at com.revature.services.ExpenseService.findAll(ExpenseService.java:25)
	at com.revature.services.ExpenseService.main(ExpenseService.java:29)
2021-03-07 10:16:40 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:16:40 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:16:40 WARN  ExpenseDAOImpl:106 - Unable to retrieve all expenses
org.postgresql.util.PSQLException: The column name resolver_email was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.ExpenseDAOImpl.findAll(ExpenseDAOImpl.java:92)
	at com.revature.services.ExpenseService.findAll(ExpenseService.java:25)
	at com.revature.services.ExpenseService.main(ExpenseService.java:29)
2021-03-07 10:17:12 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:17:12 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:17:12 WARN  ExpenseDAOImpl:106 - Unable to retrieve all expenses
org.postgresql.util.PSQLException: The column name status_id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.ExpenseDAOImpl.findAll(ExpenseDAOImpl.java:95)
	at com.revature.services.ExpenseService.findAll(ExpenseService.java:25)
	at com.revature.services.ExpenseService.main(ExpenseService.java:29)
2021-03-07 10:19:36 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:19:36 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:19:37 WARN  ExpenseDAOImpl:106 - Unable to retrieve all expenses
org.postgresql.util.PSQLException: The column name reimb_status was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.ExpenseDAOImpl.findAll(ExpenseDAOImpl.java:96)
	at com.revature.services.ExpenseService.findAll(ExpenseService.java:25)
	at com.revature.services.ExpenseService.main(ExpenseService.java:29)
2021-03-07 10:20:04 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:20:04 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:20:20 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:20:20 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:20:48 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:20:48 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 10:22:48 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 10:22:48 INFO  ConnectionUtil:52 - Connected to db
2021-03-07 14:41:33 INFO  ConnectionUtil:42 - Connection successful
2021-03-07 14:41:33 INFO  ConnectionUtil:52 - Connected to db
